### ISSUE TITLE
Error when I try to build googlechrome/howto-components

### ISSUE THREAD

**Issue by joao-parana** [GoogleChromeLabs/howto-components#113]
When I try to build googlechrome/howto-components like this

```bash
docker build -t googlechrome/howto-components .
```

I get the following error:

```
Sending build context to Docker daemon    1.2MB
Step 1/9 : FROM node:8-onbuild
# Executing 5 build triggers...
Step 1/1 : ARG NODE_ENV
 ---> Using cache
Step 1/1 : ENV NODE_ENV $NODE_ENV
 ---> Using cache
Step 1/1 : COPY package.json /usr/src/app/
 ---> Using cache
Step 1/1 : RUN npm install && npm cache clean --force
 ---> Running in 5637a5d2878b
container_linux.go:262: starting container process caused "exec: \"/bin/sh\": stat **/bin/sh: no such file or directory**"
oci runtime error: container_linux.go:262: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
```

**Comment by joao-parana** [comment]
by the way, I'm using macOS Sierra 10.12.6 and Docker Version 17.07.0-ce-rc4-mac25

**Comment by surma** [comment]
Cannot reproduce this on my end :-/

macOS 10.12.6
Docker version 17.06.0-ce, build 02c1d87
Commit a81450a4833f07452ec0a19954853c7545ae9647

I’ll see if I can get an update to 17.07, but I doubt it’ll make a difference.

A (pretty drastic) idea: Can you delete all your local docker images? `docker images -a -q | xargs -n1 docker rmi`

**Comment by robdodson** [comment]
@joao-parana did Surma's advice help?

**Comment by joao-parana** [comment]
I reset my Docker to factory defaults.

![reset_docker](https://user-images.githubusercontent.com/1621241/32702873-64cc2bbe-c7d4-11e7-8824-d4d98a398784.png)

Now works for me too. Tanks @surma and @robdodson
