### ISSUE TITLE
<form>

### ISSUE THREAD

**Issue by oskude** [GoogleChromeLabs/howto-components#120]
<form>

i tried the `<howto-checkbox>` in a `<form>` like this:

```
diff --git a/elements/howto-checkbox/demo.html b/elements/howto-checkbox/demo.html
index d4b8c4e..e2a065c 100644
--- a/elements/howto-checkbox/demo.html
+++ b/elements/howto-checkbox/demo.html
@@ -25,5 +25,16 @@ limitations under the License.
   }
 </style>
 
+<form id="daform">
 <howto-checkbox aria-labelledby="join-label"></howto-checkbox>
 <span id="join-label">Join Newsletter</span>
+<input type="submit"/>
+</form>
+
+<script>
+var form = document.querySelector("#daform");
+form.addEventListener("submit", (event)=>{
+  event.preventDefault();
+  console.dir(form);
+});
+</script>
```

after clicking submit, dev console only shows reference to the vanilla submit button:
![image](https://user-images.githubusercontent.com/157669/30918211-2409c2c6-a39e-11e7-91a5-396ccd2f0b6b.png)

am i doing it wrong?
or why does `<form>` not see `<howto-checkbox>`?

ps. this was tested on chromium 61.0.3163.100 with chrome://flags/#enable-experimental-web-platform-features enabled

**Comment by robdodson** [comment]
nope you're not doing anything wrong. This is just a limitation of using any element that is not one of the built-ins, in a form. You can see a discussion of the topic here: https://github.com/w3c/webcomponents/issues/187

It sounds like standards folks are planning to discuss this at the upcoming TPAC meeting (https://github.com/w3c/webcomponents/issues/641) so I'm hoping to see some progress there. I think we can update the howto-* docs to mention this.

**Comment by oskude** [comment]
thank you very much for the links!

> I think we can update the howto-* docs to mention this.

that would be sweet.

**Comment by robdodson** [comment]
@oskude FYI #121
