### ISSUE TITLE
The howto-radio-group example doesn't have a label

### ISSUE THREAD

**Issue by slauriat** [GoogleChromeLabs/howto-components#123]
The example has labels for each radiobutton, but not for the overall group. Looking at http://dash-elements.surma.link/0d0e37e38d2992bab729500d8efe9972d9f5501f/howto-radio-group/ I would expect a label of "Beverage" or something.

**Comment by robdodson** [comment]
Good catch. I'll see if we can use [howto-label](https://github.com/GoogleChromeLabs/howto-components/tree/master/elements/howto-label) on it. That just recently landed.

**Comment by robdodson** [comment]
Fixed with the power of fieldset
