### ISSUE TITLE
Bringing along the component's resources...

### ISSUE THREAD

**Issue by manor** [GoogleChromeLabs/howto-components#127]
What is the "official" mechanism by which a component brings along its resources (e.g. images, fonts etc.). It looks like even in the simplest case of the check-box the path is [hacked by the build script](https://github.com/GoogleChromeLabs/howto-components/blob/master/elements/howto-checkbox/howto-checkbox.js#L42) and the component is hoping that when it is used there is a relative path to its images... 

So, in order to use the check-box I must not only include the howto-checkbox.js, but I must pre-modify its code and remember to put the images in some pre-defined location? How do I know to do this? Where is this declared?

**Comment by robdodson** [comment]
You should be able to refer to the images with just relative paths in your CSS.

We did that PATH weirdness in our implementation so we could move the element over to the docs at developers.google.com/web where the image path would be different. We're planning to change things so we no longer need to do that.

**Comment by surma** [comment]
> What is the "official" mechanism by which a component brings along its resources

In the context of howto-components, there is none. As mention in the very first paragraph of the README: “They are explicitly NOT a UI library meant to be used in production.”, so we have not put any work in making them easy to use, but rather easy to read.

**Comment by manor** [comment]
The question was broader than these howto-components (I understand they are examples not products) I'm simply trying to understand how one is supposed to organize a vanilla-js web-component that one wants to share. I'm getting from the answers that basically, I tell the user of the component: "put this directory somewhere on your site and if you move any of the resources inside then it's on you to modify my code which assumes the resources are in a fixed location relative to the javascript source file which defines the component"...

**Comment by robdodson** [comment]
> "put this directory somewhere on your site and if you move any of the resources inside then it's on you to modify my code which assumes the resources are in a fixed location relative to the javascript source file which defines the component"

Yeah I think this is correct. If your element is published to npm then I don't think they should need to physically place the directory anywhere themselves, it'll just be part of the published package.
