### ISSUE TITLE
Add infos on screenreaders and how to use them to intro section

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/howto-components#26]

**Comment by robdodson** [comment]
This is a good idea but I think this content should live in Web Fundamentals. We already have stuff in our accessibility docs explaining how screen readers work and our overview (https://developers.google.com/web/fundamentals/web-components/examples/) links to those a11y docs. I think as far as howto-components are concerned, having those links back to the larger a11y doc set satisfies this issue.
