### ISSUE TITLE
Add description of CEv1 lifecycle functions to intro

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/howto-components#8]

**Comment by surma** [comment]
I have no idea what I meant with this....

**Comment by surma** [comment]
I totes remembered!

**Comment by robdodson** [comment]
Do you recall what you meant in this issue? Is it anything that we already have docs for at https://developers.google.com/web/fundamentals/web-components ?

**Comment by surma** [comment]
Yeah this can be closed now as we are not launching an independent site anymore.
